version: 2.1
jobs:
  build:
    docker:
      - image: alpine:3.7
    steps:
      - checkout
      - run:
          name: Run maven verify
          command: |
            mvn clean verify

general:
  branches:
    only:
      - ron-follow-along # list of branches to build